### PR TITLE
Update libraries and target Android Q

### PR DESCRIPTION
**Pull request by rafaeltoledo**
With the Detekt update, I also fixed some warnings pointed by it

### CODE REVIEW

**Comment by gpeal** [comment]
@rafaeltoledo Can you rebase this? Master no longer has detekt errors and there are a number of warnings here.

**Comment by rafaeltoledo** [comment]
Sure. I just need to update the CLI interface of Detekt

**Comment by gpeal** [comment]
@rafaeltoledo You have a bunch of changes due to local ide settings that aren't part of our Detekt setup. Can you revert any changes that aren't required to keep this PR focused?

**Comment by rafaeltoledo** [comment]
Those are from new Detekt rules enabled by default. Should I disable them?

**Comment by gpeal** [comment]
@rafaeltoledo `./detekt` from the root of the repo will run detekt with the config in the repo.

**Comment by rafaeltoledo** [comment]
No problem. To keep this PR concise, I will revert the Detekt update.

**Comment by jpventura** [comment]
@gpeal pull requests #364 and #367 solves the dependency bumps.

Modifications related to Roboeletric unit tests committed by @rafaeltoledo were cherry picked into them.

**Comment by jpventura** [comment]
@gpeal Fixed at #367 (thank you @rafaeltoledo for refactoring the tests). We may close #313 now.

**Comment by jpventura** [comment]
@elihart @gpeal Fixed at #367 (thank you @rafaeltoledo for refactoring the tests). We may close #313.

**Pull request closed without merging**
