### PR TITLE
Re-enable project code styles for Android Studio

### PR DESCRIPTION
**Pull request by jpventura**
### About
A project code style configuration was added at b4417f39 (along with `Dekekt` and `Ktlint` setups), however it was mistakenly marked to be ignore by the VCS at 4bd6a8a3.

In order to reestablish the previous setup, first the .[`gitignore`](https://github.com/airbnb/MvRx/blob/master/.gitignore) file was updated according [GitHub template for Android](https://github.com/github/gitignore/blob/master/Android.gitignore), covering automatic files for several IDEs and build scripts.

Finally `.idea/codeStyles` was is no longer ignored, allowing project code styles be checked in the VCS.

### Closes
  - Issue #355

### References

  - [GitHub: A collection of useful .gitignore templates](https://github.com/github/gitignore)

### CODE REVIEW

**Comment by elihart** [comment]
This looks pretty good to me, thanks for putting this up. I'll let @gpeal confirm though

**Comment by jpventura** [comment]
@gpeal @elihart wow! my name was replaced at the PR description! :joy:

**Comment by gpeal** [comment]
What happened?

**Comment by gpeal** [comment]
@jpventura Oh, the authorship? That's very strange... I'm not sure why that happened! 😢

**Comment by jpventura** [comment]
@gpeal no problemo. many more PRs shall arrive soon now we all are in quarantine :joy:

**Pull request merged**
