### PR TITLE
Use correct base classes in README.md

### PR DESCRIPTION
**Pull request by markushi**
I just added two minor tweaks to the README.md to correctly reflect the actual API.

### CODE REVIEW

**Comment by gpeal** [comment]
It's not correct to use the Base one directly. The [integration instructions](https://github.com/airbnb/MvRx/wiki/Integrating-MvRx-In-Your-App#steps-required) suggest that you create your own base class.

I think that could be clearer though. How could we update the readme to make that more clear?

**Comment by gpeal** [comment]
@markushi

**Comment by markushi** [comment]
Oh right, looks like I missed that - sorry. 
Well I guess it's a bit tricky. As a first time user I'd expect to see a working example. On the other side it's important to see that MvRx doesn't force you to a specific inheritance model.

I guess the confusing part for me was that `MvRxViewModel` is not part of MvRx. How about renaming it to `BaseViewModel` or `MyBaseViewModel`? Then it should be clear that this class is not part of MvRx.

**Comment by gpeal** [comment]
Done :) Thanks for the suggestion.

**Pull request closed without merging**
