### PR TITLE
Todomvrx unit tests

### LINKED ISSUE #31: Write unit tests for todomvrx

### PR DESCRIPTION
**Pull request by rom4ek**
Hey guys, thanks for the nice library! I was just curious about testability of the architecture (Closes #31), and decided to give it a try, so don't judge me hard :) As you don't expose the `debugMode` parameter, I was not sure how do you guys mock the `BuildConifg` behavior at airbnb, but I've done that via small `SuperReflect` lib, just so I don't like PowerMock, and that was a minor thing that prevented me from unit-testing the view model. I also didn't add tests for combining different data sources, but it can be ofc easily done.

### CODE REVIEW

**Comment by rom4ek** [comment]
@gpeal Cool, I'd love to update the PR, when you come up with something regarding debugMode handling.

**Comment by gpeal** [comment]
@BenSchwab @elihart Any ideas here?

**Comment by qbait** [comment]
Hey guys, any news about the recommended way?

**Comment by gpeal** [comment]
@qbait @rom4ek Just out of curiosity, what were you trying to trigger by forcing debug mode to be true/false?

**Comment by rom4ek** [comment]
@gpeal For me the problem is that `BuildConfig.DEBUG` returns `true` when you're running unit tests with `debug` build variant. And since the `debugMode` is `true`, the `validateState` function gets invoked, which is dependent on `android.os.Bundle`, and that one as you know doesn't exist on JVM and should be mocked, therefore the test is failing. Ofc, we could create another build type for JVM tests, but imo they should pass regardless of `BuildConfig.DEBUG` field.

**Comment by rom4ek** [comment]
@gpeal @elihart @BenSchwab  guys any updates on this? I'm still wondering how are you handling this case at airbnb. Do you have a separate build type for running JVM unit tests?

**Comment by gpeal** [comment]
@rom4ek fyi: https://github.com/airbnb/MvRx/pull/154

**Comment by gpeal** [comment]
@rom4ek For sure. Is it ready now?

**Comment by rom4ek** [comment]
@gpeal yes!

**Pull request merged**
